application: mcme-api
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# static files
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/favicon\.ico

- url: /robots.txt
  static_files: static/txt/robots.txt
  upload: static/robots.txt

- url: .*
  script: main.app




libraries:
- name: webapp2
  version: "latest"

- name: jinja2
  version: "latest"

- name: yaml
  version: "latest"

builtins:
- remote_api: on